# This is a basic workflow to help you get started with Actions

name: Merge upstream branches

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  schedule:
    # actually, ~5 minutes is the highest
    # effective frequency you will get
    - cron:  '0/5 * * * *'
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Merge upstream
        run: |
          git config --global user.name 'bobo'
          git config --global user.email 'm18518782315@163.com'
          git pull --unshallow
          git remote add upstream https://github.com/SanZangJun/es-test.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
          git fetch upstream --tags
          git push --tags
